spring:
  application:
    name: product
  datasource:
    username: root
    password: zwz520
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_in_action?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/