eureka:
  instance:
    hostname: localhost
#    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://peer2:8762/eureka/
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8761