eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    # 从分片中同步信息
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  server:
    enable-self-preservation: false
spring:
  application:
    name: slave-eureka
server:
  port: 8762