spring:
  application:
    name: client

eureka:
  instance:
    hostname: localhost
  #    hostname: peer1
  client:
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8761/eureka/
server:
  port: 8080